version: '3.1'

services:

    webp_server:
        image: n0vad3v/webp_server
        restart: always
        volumes:
            - ./webp_exhaust:/usr/src/app/webp
            - ./PATH/TO/IMG_PATH:/usr/src/app/pics
        ports:
            - 3000:3333
