version: '3.1'

services:

    webp_server:
        image: n0vad3v/webp_server
        restart: always
        volumes:
            - ./EXHAUST:/usr/src/app/webp
            - ./INTAKE:/usr/src/app/pics
        environment:
            DOCKER: yes
        ports:
            - 3000:3333
